StudioBMS/Models/ManageViewModels/ChangePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StudioBMS.Models.ManageViewModels
{
    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.",
            MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

StudioBMS/Areas/Settings/Controllers/AccountSettingsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using StudioBMS.Business.DTO.Models;
using StudioBMS.Business.Managers.Identity;
using StudioBMS.Business.Managers.Models.Impl;
using StudioBMS.Business.Managers.Models.Interfaces;
using StudioBMS.Controllers;
using StudioBMS.Models.ManageViewModels;
using StudioBMS.Models.UI;
using StudioBMS.Services;

namespace StudioBMS.Areas.Settings.Controllers
{
    [Area("Settings")]
    [Route("[area]")]
    public class AccountSettingsController : Controller
    {
        private readonly IEmailSender _emailSender;
        private readonly string _externalCookieScheme;
        private readonly ILogger _logger;

        private readonly Dictionary<MessageType, string> _messages = new Dictionary<MessageType, string>
        {
            {MessageType.Success, "PasswordUpdated"}
        };

        private readonly PersonModelSignInManager _signInManager;
        private readonly IPersonManager _personManager;
        private readonly PersonModelManager _userManager;

        public AccountSettingsController(
            PersonModelManager userManager,
            PersonModelSignInManager signInManager,
            IPersonManager personManager,
            IOptions<IdentityCookieOptions> identityCookieOptions,
            IEmailSender emailSender,
            ILoggerFactory loggerFactory)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _personManager = personManager;
            _externalCookieScheme = identityCookieOptions.Value.ExternalCookieAuthenticationScheme;
            _emailSender = emailSender;
            _logger = loggerFactory.CreateLogger<ManageController>();
        }

        [HttpGet]
        public async Task<IActionResult> Index(MessageType? message)
        {
            if (message.HasValue)
                ViewData["Message"] =
                    new MessageViewModel { Message = _messages[message.Value], Type = MessageType.Success };
            return View(await _userManager.FindByEmailAsync(User.Identity.Name));
        }

        [HttpPost]
        public async Task<IActionResult> Update(PersonModel model)
        {
            var entity = await _personManager.GetAsync(model.Id);
            entity.FirstName = model.FirstName;
            entity.LastName = model.LastName;

            if (entity.UserName != model.UserName)
            {
                entity.Email = model.UserName;
                entity.UserName = model.UserName;
                entity.NormalizedEmail = model.UserName.ToUpper().Normalize();
                entity.NormalizedUserName = model.UserName.ToUpper().Normalize();
                await _signInManager.SignOutAsync();
            }
            entity.Language = model.Language;
            entity.Birthday = model.Birthday;
            entity.PhoneNumber = model.PhoneNumber;
            await _personManager.UpdateAsync(entity);
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
                $"c={model.Language}|uic={model.Language}");
            return RedirectToAction("Index");
        }

        [HttpGet("password")]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost("password")]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var user = await GetCurrentUserAsync();
            if (user != null)
            {
                var result = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    _logger.LogInformation(3, "User changed their password successfully.");
                    return RedirectToAction(nameof(Index), new { Message = MessageType.Success });
                }
                AddErrors(result);
                return View(model);
            }
            return RedirectToAction(nameof(Index), new { Message = MessageType.Danger });
        }


        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
                ModelState.AddModelError(string.Empty, error.Description);
        }

        private Task<PersonModel> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }
    }
}

StudioBMS/Areas/Settings/Views/AccountSettings/ChangePassword.cshtml
@inject IHtmlLocalizer<ModelResource> ModelLocalizer
@inject IHtmlLocalizer<PageTitleResource> TitleLocalizer
@using StudioBMS.Models.ManageViewModels
@model ChangePasswordViewModel
@{
    var title = TitleLocalizer["ChangePassword"];
    ViewData["Title"] = title;
    ViewData["H1"] = title;
}
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-body row">
                <form asp-area="Settings" asp-controller="AccountSettings" asp-action="ChangePassword" method="post" class="form-horizontal col-lg-6 col-lg-offset-3">
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger form-group"></div>
                    <div class="form-group">
                        <label>@ModelLocalizer[nameof(Model.OldPassword)]</label>
                        <input asp-for="OldPassword" class="form-control" placeholder="@ModelLocalizer[nameof(Model.OldPassword)]"/>
                        <span asp-validation-for="OldPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>@ModelLocalizer[nameof(Model.NewPassword)]</label>
                        <input asp-for="NewPassword" class="form-control" placeholder="@ModelLocalizer[nameof(Model.NewPassword)]"/>
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>@ModelLocalizer[nameof(Model.ConfirmPassword)]</label>
                        <input asp-for="ConfirmPassword" class="form-control" placeholder="@ModelLocalizer[nameof(Model.ConfirmPassword)]"/>
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-4 col-md-4">
                            <button type="submit" class="btn btn-primary btn-block">@TitleLocalizer["Submit"]</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

StudioBMS/Areas/Settings/Views/AccountSettings/Index.cshtml
@inject IHtmlLocalizer<ModelResource> Localizer
@inject IHtmlLocalizer<PageTitleResource> TitleLocalizer

@model PersonModel
@{
    var title = TitleLocalizer["Settings"];
    ViewData["Title"] = title;
    ViewData["H1"] = title;
}
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <form asp-area="Settings" asp-controller="AccountSettings" asp-action="Update" method="post">
                    <input type="hidden" asp-for="Id"/>
                    <input type="hidden" asp-for="Workshop.Id"/>
                    <div class="row">
                        <div class="col-lg-6 form-group">
                            <label>@Localizer[nameof(Model.LastName)]</label>
                            <input type="text" asp-for="LastName" placeholder="@Localizer[nameof(Model.LastName)]" class="form-control"/>
                        </div>
                        <div class="col-lg-6 form-group">
                            <label>@Localizer[nameof(Model.FirstName)]</label>
                            <input type="text" asp-for="FirstName" placeholder="@Localizer[nameof(Model.FirstName)]" class="form-control"/>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-lg-6">
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label>@Localizer["EMail"]</label>
                                    <input type="text" asp-for="UserName" placeholder="@Localizer[nameof(Model.Email)]" class="form-control"/>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label>@Localizer[nameof(Model.PhoneNumber)]</label>
                                    <input type="text" asp-for="PhoneNumber" placeholder="@Localizer[nameof(Model.PhoneNumber)]" class="form-control"/>
                                </div>
                            </div>

                        </div>
                        <div class="col-lg-6">
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label>@Localizer["Language"]</label>
                                    <select class="form-control" asp-for="Language">
                                        <option value="en">@Localizer["English"]</option>
                                        <option value="uk">@Localizer["Ukrainian"]</option>
                                        <option value="ru">@Localizer["Russian"]</option>
                                    </select>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label>@Localizer[nameof(Model.Birthday)]</label>
                                    <div class="input-group datetimepicker" data-locale="@CultureInfo.CurrentCulture.Name" data-format="YYYY-MM-DD">
                                        <input asp-for="Birthday" asp-format="{0:yyyy-MM-dd}" placeholder="@Localizer[nameof(Model.Birthday)]" class="form-control"/>
                                        <span class="input-group-addon">
                                            <span class="fa fa-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-3 ">
                            <a asp-action="ChangePassword" class="btn btn-link btn-block">@TitleLocalizer["ChangePassword"]</a>
                        </div>
                        <div class="col-xs-3 col-xs-offset-6">
                            <button class="btn btn-primary btn-block">@TitleLocalizer["Save"]</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>